project:
  output-dir: _output

jupyter: plant-diseases-segmentation

format:
  beamer:
    theme: Madrid
    colortheme: dolphin
    fonttheme: professionalfonts
    pdf-engine: xelatex
    aspectratio: 169
    incremental: false
    slide-level: 2
    include-in-header: header.tex
