project:
  output-dir: _output

jupyter: plant-diseases-segmentation

format:
  beamer:
    theme: Madrid
    colortheme: dolphin
    fonttheme: professionalfonts
    pdf-engine: xelatex
    incremental: false
    slide-level: 2
    include-in-header: header.tex
  pdf:
    documentclass: article
    geometry:
      - top=25mm
      - left=25mm
      - right=25mm
      - bottom=25mm
